In [1]:
import numpy as np
import torch
import polars as pl

In [2]:
from deep_parity.model import MLP

/Users/dashiell/workspace/deep-parity/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [25]:
n = 10
model = MLP(n, 256, 512)

In [26]:
import numpy as np
from deep_parity.boolean_cube import generate_all_binary_arrays, fourier_transform

all_binary_arrays = torch.from_numpy(generate_all_binary_arrays(n)).to(torch.float32)
all_parities = all_binary_arrays.sum(dim=1) % 2

In [27]:
logits, cache = model.run_with_cache(all_binary_arrays)

In [28]:
linear_preacts = cache['hook_linear']

In [29]:
ft = fourier_transform(linear_preacts.T)

In [34]:
ft.shape

torch.Size([512, 1024])

In [32]:
linear_preacts.shape

torch.Size([1024, 512])

In [31]:
2 ** n

1024

In [36]:
ft.shape
linear_df = pl.DataFrame(ft.T.numpy(), schema=[str(i) for i in range(ft.shape[0])])

In [38]:
base_df = pl.DataFrame({
    'bits': all_binary_arrays.numpy(), 
    'parities': all_parities.numpy(), 
    'degree': all_binary_arrays.sum(dim=1).numpy()
}).with_columns(indices=pl.col('bits').arr.to_list().list.eval(pl.arg_where(pl.element() == 1)))

In [39]:
data = pl.concat([base_df, linear_df], how='horizontal')

In [46]:
data.head()

shape: (5, 516)
┌──────────────┬──────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ bits         ┆ parities ┆ degree ┆ indices   ┆ … ┆ 508       ┆ 509       ┆ 510       ┆ 511       │
│ ---          ┆ ---      ┆ ---    ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ array[f32,   ┆ f32      ┆ f32    ┆ list[u32] ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32       │
│ 10]          ┆          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════════╪══════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ [0.0, 0.0, … ┆ 0.0      ┆ 0.0    ┆ []        ┆ … ┆ -1.277706 ┆ 8.795528  ┆ 6.812182  ┆ -0.072817 │
│ 0.0]         ┆          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ [0.0, 0.0, … ┆ 1.0      ┆ 1.0    ┆ [9]       ┆ … ┆ 0.338682  ┆ -0.0546   ┆ -1.574025 ┆ -1.356707 │
│ 1.0]         ┆          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ [0.0, 0.0, … ┆ 1.0      ┆ 1.0    ┆ [8]       ┆ … ┆ 0.905718  ┆ -1.241576 ┆ 0.091067  ┆ -0.057909 │
│ 0.0]         ┆          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ [0.0, 0.0, … ┆ 0.0      ┆ 2.0    ┆ [8, 9]    ┆ … ┆ 3.6671e-8 ┆ 2.3938e-9 ┆ 9.8255e-8 ┆ 2.9802e-8 │
│ 1.0]         ┆          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ [0.0, 0.0, … ┆ 1.0      ┆ 1.0    ┆ [7]       ┆ … ┆ -0.723198 ┆ -1.09784  ┆ 0.531416  ┆ 0.592896  │
│ 0.0]         ┆          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────────┴──────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [48]:
data.select(pl.exclude('bits', 'parities', 'indices')).unpivot(index='degree').group_by('degree', 'variable').agg(pl.col('value').pow(2).sum())

shape: (5_632, 3)
┌────────┬──────────┬────────────┐
│ degree ┆ variable ┆ value      │
│ ---    ┆ ---      ┆ ---        │
│ f32    ┆ str      ┆ f32        │
╞════════╪══════════╪════════════╡
│ 3.0    ┆ 129      ┆ 1.1206e-12 │
│ 10.0   ┆ 395      ┆ 2.9747e-15 │
│ 8.0    ┆ 78       ┆ 1.4488e-13 │
│ 10.0   ┆ 132      ┆ 6.9940e-15 │
│ 10.0   ┆ 334      ┆ 1.1026e-14 │
│ …      ┆ …        ┆ …          │
│ 4.0    ┆ 273      ┆ 8.7804e-13 │
│ 8.0    ┆ 63       ┆ 1.0069e-13 │
│ 4.0    ┆ 206      ┆ 2.2718e-12 │
│ 5.0    ┆ 257      ┆ 1.2992e-12 │
│ 9.0    ┆ 69       ┆ 2.8302e-14 │
└────────┴──────────┴────────────┘

In [22]:
base_df.with_columns(indices=pl.col('bits').arr.to_list().list.eval(pl.arg_where(pl.element() == 1)))

shape: (1_048_576, 4)
┌───────────────────┬──────────┬────────┬──────────────┐
│ bits              ┆ parities ┆ degree ┆ indices      │
│ ---               ┆ ---      ┆ ---    ┆ ---          │
│ array[f32, 20]    ┆ f32      ┆ f32    ┆ list[u32]    │
╞═══════════════════╪══════════╪════════╪══════════════╡
│ [0.0, 0.0, … 0.0] ┆ 0.0      ┆ 0.0    ┆ []           │
│ [0.0, 0.0, … 1.0] ┆ 1.0      ┆ 1.0    ┆ [19]         │
│ [0.0, 0.0, … 0.0] ┆ 1.0      ┆ 1.0    ┆ [18]         │
│ [0.0, 0.0, … 1.0] ┆ 0.0      ┆ 2.0    ┆ [18, 19]     │
│ [0.0, 0.0, … 0.0] ┆ 1.0      ┆ 1.0    ┆ [17]         │
│ …                 ┆ …        ┆ …      ┆ …            │
│ [1.0, 1.0, … 1.0] ┆ 1.0      ┆ 19.0   ┆ [0, 1, … 19] │
│ [1.0, 1.0, … 0.0] ┆ 0.0      ┆ 18.0   ┆ [0, 1, … 17] │
│ [1.0, 1.0, … 1.0] ┆ 1.0      ┆ 19.0   ┆ [0, 1, … 19] │
│ [1.0, 1.0, … 0.0] ┆ 1.0      ┆ 19.0   ┆ [0, 1, … 18] │
│ [1.0, 1.0, … 1.0] ┆ 0.0      ┆ 20.0   ┆ [0, 1, … 19] │
└───────────────────┴──────────┴────────┴──────────────┘

In [24]:
def make_base_parity_dataframe(n):
    all_binary_data = generate_all_binary_arrays(n)
    all_degrees = all_binary_data.sum(axis=1)
    all_parities = all_degrees % 2


    base_df = pl.DataFrame({
        'bits': all_binary_data, 
        'parities': all_parities, 
        'degree': all_degrees
    })
    base_df = base_df.with_columns(
        indices=pl.col('bits').arr.to_list().list.eval(pl.arg_where(pl.element() == 1))
    )
    return base_df


make_base_parity_dataframe(10).head()

shape: (5, 4)
┌───────────────┬──────────┬────────┬───────────┐
│ bits          ┆ parities ┆ degree ┆ indices   │
│ ---           ┆ ---      ┆ ---    ┆ ---       │
│ array[u8, 10] ┆ u64      ┆ u64    ┆ list[u32] │
╞═══════════════╪══════════╪════════╪═══════════╡
│ [0, 0, … 0]   ┆ 0        ┆ 0      ┆ []        │
│ [0, 0, … 1]   ┆ 1        ┆ 1      ┆ [9]       │
│ [0, 0, … 0]   ┆ 1        ┆ 1      ┆ [8]       │
│ [0, 0, … 1]   ┆ 0        ┆ 2      ┆ [8, 9]    │
│ [0, 0, … 0]   ┆ 1        ┆ 1      ┆ [7]       │
└───────────────┴──────────┴────────┴───────────┘

In [ ]:
def make_base_parity_dataframe(n):
    all_binary_data = generate_all_binary_arrays(n)
    all_degrees = all_binary_data.sum(axis=1)
    all_parities = all_degrees % 2


    base_df = pl.DataFrame({
        'bits': all_binary_data, 
        'parities': all_parities, 
        'degree': all_degrees
    })
    base_df = base_df.with_columns(
        indices=pl.col('bits').arr.to_list().list.eval(pl.arg_where(pl.element() == 1))
    )
    return base_df


def calc_power_contributions(tensor, n):
    base_df = make_base_parity_dataframe(n)
    ft = fourier_transform(tensor)
    linear_df = pl.DataFrame(
        ft.T.numpy(),
        schema=[str(i) for i in range(ft.shape[0])]
    )
    data = pl.concat([base_df, linear_df], how='horizontal')

    power_vals = torch.cat([power_contribs[irrep].unsqueeze(0) for irrep in irreps], dim=0)
    val_data = pl.DataFrame(power_vals.detach().cpu().numpy(), schema=[f'dim{i}' for i in range(power_vals.shape[1])])

    return val_data, power_contribs


def fourier_analysis(model, n, epoch):
    W = model.linear.weight
    embeds = model.embed.weight.T
    embed_dim = embeds.shape[0]
    linear = (W @ embeds).T
    embed_power_df = calc_power_contributions(linear, n).with_columns(pl.lit(epoch).alias('epoch'))
    return embed_power_df

In [2]:
def generate_binary_array_efficient(n):
    # Create an array of all possible numbers for n bits
    numbers = np.arange(2**n, dtype=np.uint32)
    
    # Use broadcasting with a single bitwise operation
    return ((numbers[:, np.newaxis] >> np.arange(n)[::-1]) & 1).astype(np.uint8)


generate_binary_array_efficient(25)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8)